# --- INFORMASI DASAR SITUS ---
# Ini adalah pengaturan utama untuk situs Anda.
# Ganti nilainya dengan informasi Anda sendiri.

title: Judul Situs Anda
email: email-anda@contoh.com
description: >- # Tanda `>-` berarti baris baru akan diabaikan hingga paragraf berikutnya.
  Ini adalah deskripsi singkat situs Anda. Deskripsi ini akan muncul
  di hasil pencarian Google dan digunakan oleh plugin SEO.
url: "https://nama-pengguna.github.io" # URL utama situs Anda. PENTING: Jangan diakhiri dengan /
baseurl: "/nama-repositori" # Gunakan jika situs Anda ada di dalam subdirektori, misal: https://nama-pengguna.github.io/nama-repositori/
                           # Jika situs Anda langsung di domain utama, biarkan kosong ""


# --- PENGATURAN BUILD ---
# Konfigurasi teknis bagaimana Jekyll akan membangun situs Anda.
# Biasanya tidak perlu diubah jika menggunakan GitHub Pages.

markdown: kramdown
highlighter: rouge
theme: minima # Anda bisa menggunakan tema lain yang didukung GitHub Pages, misalnya: jekyll-theme-cayman, jekyll-theme-merlot

plugins:
  - jekyll-feed       # Membuat feed Atom/RSS untuk post Anda
  - jekyll-seo-tag    # Menambahkan meta tag untuk SEO secara otomatis
  - jekyll-sitemap    # Membuat sitemap.xml untuk membantu mesin pencari


# --- PENGATURAN KONTEN ---
# Mengatur bagaimana konten Anda ditampilkan.

# Contoh struktur permalink untuk postingan blog
permalink: /blog/:year/:month/:day/:title/

# Pengaturan paginasi (jika Anda memiliki banyak postingan)
paginate: 5
paginate_path: "/blog/page:num/"


# --- KOLEKSI ---
# Berguna jika Anda ingin mengelompokkan konten selain 'posts'.
# Contoh: portofolio atau proyek.
# collections:
#   projects:
#     output: true
#     permalink: /projects/:path/


# --- VARIABEL KUSTOM ---
# Anda bisa menambahkan variabel sendiri di sini untuk digunakan di seluruh situs.

# Informasi Penulis/Pemilik
author:
  name: "Nama Lengkap Anda"
  twitter: "akun_twitter_anda"
  github: "akun_github_anda"

# Tautan Sosial Media
social:
  - title: twitter
    url: https://twitter.com/akun_twitter_anda
  - title: github
    url: https://github.com/akun_github_anda
  - title: linkedin
    url: https://www.linkedin.com/in/akun_linkedin_anda

# Integrasi dengan layanan pihak ketiga (contoh: Google Analytics)
google_analytics: "UA-000000-0" # Ganti dengan Tracking ID Anda


# --- PENGECUALIAN ---
# Berkas atau folder yang tidak akan disertakan saat situs di-build.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE.txt
